### ISSUE TITLE
Option to set classpath

### ISSUE THREAD

**Issue by toroidal-code** [mhayashi1120/Emacs-langtool#11]
I'm working on Arch Linux, and the way that packages install, they don't expose the proper classpaths using environment variables, but instead create wrapper scripts that contain the proper "-cp /some/path/here:/another/path/" in the command

for example:
```
#!/bin/bash
[...]
CP=/usr/share/languagetool
for name in /usr/share/java/languagetool/*.jar ; do
  CP=$CP:$name
done
[...]
CLI_command='org.languagetool.commandline.Main'
[...]
"$JAVA_HOME/bin/java" -cp $CP $CLI_command"
```

So whenever I try to run langtool-check or any of the other commands I get a rather lengthy "NoClassDefFoundError", and I can't set langtool-java-bin as the command with the classpath added, since langtool.el checks whether the set binary exists or not.

I was thinking this could be avoided by having some sort of variable like "langtool-java-classpath" that is empty by default, and then checking whether it's empty. If not, a `"-cp " (langtool-java-classpath)` could be added to the args list on line 251.

**Comment by mhayashi1120** [comment]
Thanks for the report.

+ Is your problem same as this?

https://github.com/mhayashi1120/Emacs-langtool/issues/8

+ If this is your `langtool-java-bin` script:

```bash
#!/bin/bash
[...]
CP=/usr/share/languagetool
for name in /usr/share/java/languagetool/*.jar ; do
  CP=$CP:$name
done
[...]
CLI_command='org.languagetool.commandline.Main'
[...]
"$JAVA_HOME/bin/java" -cp $CP $CLI_command"
```

Pass through arguments from Emacs to your script like following.

```bash
#!/bin/bash
[...]
CP=/usr/share/languagetool
for name in /usr/share/java/languagetool/*.jar ; do
  CP=$CP:$name
done
[...]
"$JAVA_HOME/bin/java" -cp $CP "$@"
```

It may work for you. Please try it.

**Comment by toroidal-code** [comment]
My `langtool-java-bin` is `/usr/bin/java` and my `langtool-language-tool-jar` is `/usr/share/java/languagetool/languagetool-commandline.jar`

The [full script](https://gist.github.com/toroidal-code/b002dedd1e8a8a83de8d) is more complex, and I'm a bit hesitant to go changing things that are provided by Arch's languagetool package, as it feels like this is more of an problem in how the command is being executed on the emacs side than outside on the OS-side.

**Comment by toroidal-code** [comment]
I created a fork and wrote out what I was thinking of, e0158a40a5ee0c3af080388834d7877d0349f9ea, and it seems to be working perfectly.

Would you like me to make a pull request for it?

**Comment by mhayashi1120** [comment]
Yes, please send it.
