### ISSUE TITLE
Symbol's function definition is void: gv-define-simple-setter

### ISSUE THREAD

**Issue by wetneb** [mhayashi1120/Emacs-langtool#13]
After installing the extension as indicated (I had to install cl-lib.el as well), I get the following error when launching `emacs`:

<pre>
Symbol's function definition is void: gv-define-simple-setter
</pre>

**Comment by mhayashi1120** [comment]
What is version of your emacs?
Probablly it is not a langtool.el error. It's cl-lib one.

Old cl-lib may resolve your problem.

https://elpa.gnu.org/packages/cl-lib.html

**Comment by wetneb** [comment]
Thanks a lot, it works! The version of cl-lib I had was older, the newest works fine with Emacs 23.4.1.
