### ISSUE TITLE
"require 'langtool" causes error

### ISSUE THREAD

**Issue by MagisDing** [mhayashi1120/Emacs-langtool#14]
I just updated package"langtool" via melpa,  and got the notification of error "wrong error argument :stringp, nil". I checked my .init.el, my setting comes below:
> 
(require 'langtool)
(setq langtool-language-tool-jar "/usr/local/Cellar/languagetool/2.8/libexec/languagetool-commandline.jar"
      langtool-mother-tongue "en"
      langtool-disabled-rules '("WHITESPACE_RULE"
                                             "EN_UNPAIRED_BRACKETS"
                                             "COMMA_PARENTHESIS_WHITESPACE"
                                             "EN_QUOTES"))
(global-set-key (kbd "<f7>") 'langtool-check-buffer)
(global-set-key (kbd "M-<f7>") 'langtool-correct-buffer)
 
 I surprisingly found out this issue could be "fixed" by commenting "require 'langtool", all the functions work well,is this a bug?

**Comment by mhayashi1120** [comment]
Yes, it's bug ;-) Sorry for your inconvenience.
Thanks for the report anyway.
