### ISSUE TITLE
LangTool command does not work

### ISSUE THREAD

**Issue by swarnendubiswas** [mhayashi1120/Emacs-langtool#15]
I am using use-package to load langtool. This is my configuration.

```
(use-package langtool
  :ensure t
  :init
  (setq langtool-language-tool-jar (concat user-emacs-directory "packages/LanguageTool-3.0/languagetool-commandline.jar")
        langtool-java-classpath (concat user-emacs-directory "packages/LanguageTool-3.0")
        langtool-default-language "en-US"
        langtool-java-bin "/usr/bin/java"))
```

However, when I invoke langtool-check on a buffer, I get the following error: 

```Error: Could not find or load main class org.languagetool.commandline.Main.```

I am using langtool for desktop. Is this what I should use?

I enabled langtool debug, here is the output:

```/usr/bin/java: (-cp ~/.emacs.d/packages/LanguageTool-3.0 org.languagetool.commandline.Main -c ascii -l en-US -d  -m en <xxx.txt>)```

However, the following command works from the terminal:
```/usr/bin/java -jar languagetool-commandline.jar  -c ascii -l en-US -d  -m en  <xxx.txt>```

**Comment by mhayashi1120** [comment]
Thanks for the report.

Hmm, please try to remove `langtool-java-classpath' from your setting.

```
(setq langtool-java-classpath nil)
```

**Comment by swarnendubiswas** [comment]
Right, I got it to work after seeing the source .el file. You do mention "alternatively" in the README.
