### ISSUE TITLE
Ability to use LangTool launcher

### ISSUE THREAD

**Issue by caadar** [mhayashi1120/Emacs-langtool#24]
Currently `langtool-language-tool-jar` or `langtool-java-classpath` setting is required.

But e.g. Gentoo distro provide executable standalone launcher for LangTool, running it manually without that is a pain.

So consider adding a way to use standalone LangTool launcher to work and just set it's path, say `/usr/bin/languagetool`.

**Comment by mhayashi1120** [comment]
Sorry for this late response. 

Please try the new branch 1.7.x .
That have `langtool-bin' new customize variable.

```
(setq langtool-bin "/usr/bin/languagetool")
```

**Comment by caadar** [comment]
It seems work. Thank you!
