### ISSUE TITLE
Is the package still being maintained? 

### ISSUE THREAD

**Issue by justintaft** [mhayashi1120/Emacs-langtool#32]
I've created a fork  at https://github.com/justintaft/Emacs-langtool/tree/httpserver

* Long running Langtool HTTPServer is used. Grammar checks are now quick without additional JVM spinup. 
* Added support to disable grammar highlights based on typefaces (such as markdown code blocks).
* System tests added and run by travis.

Please let me know if I should create a Pull request. I can create a new package if this package is now not maintained.

**Comment by mhayashi1120** [comment]
Great! Please open pull request.

**Comment by justintaft** [comment]
Hey @mhayashi1120. I've been using my forked version for a bit and it's pretty stable. However, there are some breaking changes:

1. Users have to install Java 8
2. Users have to obtain new version of Language Tool
3. Users have to updating custom variables.

If my forked version is merged back into your version, then LangTool may break for users already have it installed. Refactoring the code to support multiple versions of Language Tool will take some effort, but I'm quite busy and won't have time to do so soon. 

How do you think we should proceed? Should a new repository be created with changes, and a new recipe submitted to Melpa?

**Comment by mhayashi1120** [comment]
Sorry for the late response.

I don't want breaking changes.
And don't mind about your fork and new Melpa recipe.
Thanks for your consideration.
