### ISSUE TITLE
Setting langtool-bin not respected in langtool--checker-mode

### ISSUE THREAD

**Issue by mgttlinger** [mhayashi1120/Emacs-langtool#37]
I am using NixOs where langtool is wrapped in a bash script to have a specific version an java available so I need (not strictly necessary but huuuge hacks otherwise) to use `langtool-bin`. However, setting this doesn't work given that `langtool--checker-mode` does not check this setting.

**Comment by contrun** [comment]
I am also on nixos facing the same problem.

**Comment by mgttlinger** [comment]
I guess this can be closed now since the patch has been merged
