### ISSUE TITLE
Is there a way to use Emacs-langtool with already running Langtool server?

### ISSUE THREAD

**Issue by berhoel** [mhayashi1120/Emacs-langtool#45]
I am starting a Langtool-server with my system start, which, I guess, leads to the error message

  langtool-server--rendezvous: Failed to start LanguageTool Server.

when I am setting langtool-language-tool-server-jar. I can use langtool-server-user-arguments to start a second LanguageTool server instance, but I think it would be nicer to reuse the already running instance.

**Comment by justintaft** [comment]
I've built a version which does just that. Still need to polish it up. https://github.com/justintaft/Emacs-langtool/tree/httpserver
