### ISSUE TITLE
Allow running languagetool in a docker

### ISSUE THREAD

**Issue by To1ne** [mhayashi1120/Emacs-langtool#66]
I've been meaning to try this package, but I don't want to install Java on my machine. So it would be great if it allows you to run languagetool in a docker.

**Comment by Ddscully** [comment]
I can run [docker-languagetool](https://github.com/Erikvl87/docker-languagetool) and use this package with it's setting number 3. The Http client.

**Comment by To1ne** [comment]
Fair enough. I don't have time to test this now, but I'm closing this issue because it's resolved.
