### ISSUE TITLE
Adding langtool to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [mhayashi1120/Emacs-langtool#67]
Hi,

would you be interested in having langtool added to [NonGNU ELPA](https://elpa.nongnu.org).  It would allow more people to install stable releases of the package OOTB.  It see that there there are a few issues with maintenance and a number of issues and pull requests that ought to be addressed.  If you are OK with it, you could add me as a contributor to the GitHub project and I could try to address some of these to prepare a new release.

**Comment by mhayashi1120** [comment]
I have been absent from Emacs for a while, so I am not familiar with the recent Emacs package situation, but from what I read here, I think melpa should be sufficient.


You could add following to your .emacs:

```
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
```
